//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int Codigo { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Expiracion { get; set; }
    
        public virtual Cuenta Cuenta1 { get; set; }
    }
}
